### ISSUE TITLE
Systemd stops Service when started by timer

### ISSUE THREAD

**Issue by jstenvall-ducksify** [0x0I/ansible-role-systemd#53] opened 2021-12-02 16:02 UTC
## Description

A timer starts an `ansible` playbook that in turn updates the definitions of `systemd` unit files. When being executed, the role ensures that the running state conforms to the value of `unit_item.state` or `_default_unit_state`. Since it is started by a systemd timer is not supposed to be enabled, hence the service is shutdown.

Here's an example output from journald:

    ...
    Dec 02 15:47:35 testserver ansible-systemd[899197]: Invoked with name=ansible_run.timer state=started enabled=True daemon_reload=False daemon_reexec=False scope=system no_block=False force=None masked=None
    Dec 02 15:47:35 testserver sudo[899195]: pam_unix(sudo:session): session closed for user root
    Dec 02 15:47:35 testserver run_ansible.sh[886121]: ok: [testserver.test.com] => (item=ansible_run.timer)
    ...
    Dec 02 15:47:35 testserver ansible-systemd[899227]: Invoked with name=ansible_run.service state=stopped enabled=False daemon_reload=False daemon_reexec=False scope=system no_block=False force=None masked=None
    Dec 02 15:47:35 testserver systemd[1]: Stopping Service Run Ansible...
    Dec 02 15:47:35 testserver sudo[899225]: pam_unix(sudo:session): session closed for user root
    Dec 02 15:47:35 testserver run_ansible.sh[886121]: Terminated
    Dec 02 15:47:35 testserver systemd[1]: ansible_run.service: Main process exited, code=killed, status=15/TERM
    ...

The unit does not contain a value for the state, it is set to the value of `_default_unit_enabled`, so the service must be stopped.

## Remediation

Not sure how to fix this. Maybe a flag saying that the state is managed (by a timer) or not.

```yaml
unit_config:
  - name: "Test Service"
    manage_state: false
    Unit:
      Description: Service Test
    Service:
      User: test_user
      Group: test_user
      ExecStart: /usr/bin/ls /etc/fstab
    Install:
      WantedBy: multi-user.target
  - name: "Test Timer"
    type: timer
    enabled: true
    state: started
    Unit:
      Description: Timer Test
    Timer:
      OnCalendar: "*-*-* 4:00:00"
      Unit: "test_service.service"
    Install:
      WantedBy: timers.target
```

This is the modified launch.yml:

```yaml
- name: Activate configured Systemd units
  become: true
  when: unit_config is defined and unit_config|length > 0 and (unit_item.type is not defined or unit_item.type != 'conf')
  vars:
    _this_unit_state: "{{ omit if (unit_item.manage_state is defined and not unit_item.manage_state) else _default_unit_state }}"
  systemd:
    name: "{{ unit_item.name }}.{{ unit_item.type | default(_default_unit_type) }}"
    state: "{{ unit_item.state | default(_this_unit_state) }}"
    enabled: "{{ unit_item.enabled | default(_default_unit_enabled) }}"
  loop: "{{ unit_config }}"
  loop_control:
    loop_var: unit_item
    label: "{{ unit_item.name }}.{{ unit_item.type|default(_default_unit_type) }}"
  tags:
    - launch
```

The hash `unit_item` either contains a boolean flag `manage_state`, or not.

What do you think?

**Comment by jstenvall-ducksify** [comment] 2021-12-08 14:53
I've implemented these changes and #itworksforme. Not sure how tou would test this feature though.

**Comment by 0x0I** [comment] 2021-12-10 18:09
Hey  @jstenvall-ducksify, apologies for the delay in response - the message almost got lost in my noisy inbox (it's become a lot noisier recently with a few projects I've started following).

So I'm not quite sure I understand the issue/proposed change. Seems like a user could just create a playbook which, for example, generates a service (initially disabled/stopped) and a timer that is set to activate the service at some time specification (as is pretty customary/typical). Management of the service state with a playbook, on subsequent runs let's say, feels like an override and probably should be explicitly handled as such if desired.

Likely missing something so definitely interested in discussing more to get a better feel for the problem being addressed here though.

**Comment by jstenvall-ducksify** [comment] 2021-12-13 10:03
No worries. I know that this was hard to describe in a clear way. :( 

Imagine that you run a playbook that performs the setup of all systemd services and timers. When you execute the playbook it looks like:

```bash
    ansible-playbook -i inventory playbook-systemd.yaml
```

This works when you run it manually; all units found in the hash `unit_config` are managed properly, all states are set, timers are activated etc. This works perfectly.

However, if one of the systemd services that you configure using this role, is running the above playbook, we encounter this issue. Please pay attention to the the log line below:

```bash
Dec 02 15:47:35 testserver ansible-systemd[899227]: Invoked with name=ansible_run.service state=stopped enabled=False daemon_reload=False daemon_reexec=False scope=system no_block=False force=None masked=None
```

It states that the service must be `state=stopped` and `enabled=False`. But when the service is started by the timer, and it runs, it is not in state `stopped`. Hence the service is stopped in the middle of its execution, before the finishes:

```bash
Dec 02 15:47:35 testserver systemd[1]: Stopping Service Run Ansible...
Dec 02 15:47:35 testserver sudo[899225]: pam_unix(sudo:session): session closed for user root
Dec 02 15:47:35 testserver run_ansible.sh[886121]: Terminated
Dec 02 15:47:35 testserver systemd[1]: ansible_run.service: Main process exited, code=killed, status=15/TERM
```

Does this explain the issue better?

**Comment by jstenvall-ducksify** [comment] 2022-03-03 14:46
=> Help wanted... I've supplied a solution that I've tried and proved working. This could be easily fixed using the code I supplied.

**Comment by 0x0I** [comment] 2022-03-08 18:02
Hey, apologies for the delay in response @jstenvall-ducksify! Things have been a bit hectic lately. But yea, duly noted and I appreciate your solution for sure. Will take another look and hopefully get things merged soon.

**Comment by 0x0I** [comment] 2022-03-08 20:11
No worries - the tests and CI pipeline are in an intermediary/inoperable state atm. The tests need to either be updated to circumvent an SSH issue with the current `test-kitchen` setup or migrated to make use of something like `molecule`. I've been kind of conflicted as to what makes the most sense here..hence the stagnation in terms of updates. CI also needs to be migrated to make use of CircleCI, considering TravisCI's deprecation of its default/free service for public repos, in order to be reactivated and triggered on each PR.

Honestly, your solution seems pretty reasonable and I hesitated to submit your change since it wasn't all the way clear to me how common/serious of an issue this is. We can always revert if any major regressions appear so I'm for merging. Do you want to go ahead and submit a PR?

**Comment by 0x0I** [comment] 2022-03-08 20:15
Also note the [Contributing.md](https://github.com/0x0I/ansible-role-systemd/blob/master/CONTRIBUTING.md) for guidance on running tests. Really all you need to run locally is an installation of Ruby. I recommend something like [rvm](https://rvm.io/) to manage Ruby installs.

**Comment by jstenvall-ducksify** [comment] 2022-03-08 20:18
Sure, I'll create the PR tomorrow. I'll try to keep the naming standard already in place.

I'm certain that `molecule` is the way forward regarding testing.

PS: Sorry, I'm really allergic against Ruby. In my previous life I worked a lot with Puppet and custom modules.

**Comment by 0x0I** [comment] 2022-03-08 23:42
> Sure, I'll create the PR tomorrow. I'll try to adhere to the naming standard already in place.
> 

Right on, sounds good!

> I'm certain that `molecule` is the way forward regarding testing.
> 
> PS: Sorry, I'm really allergic against Ruby. In my previous life I worked a lot with Puppet and custom modules.

Haha I feel it and same here for the most part (re: being allergic to Ruby). I worked with Puppet, Chef and test-kitchen quite a bit prior to creating most of the Ansible roles and opted for familiarity when choosing `test-kitchen`. Certain is a pretty strong word though I'm mostly convinced :) I appreciate that kitchen supports multiple IaC solutions, as opposed to molecule which is limited to Ansible, but supporting projects in Chef, Puppet etc seems a lot less of a priority these days.

**Closed** 2022-03-22 09:36 UTC
Labels: help wanted
